### ISSUE TITLE
1.5.2 and 1.6.X client kick some server

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupportBungee#6]
Here is the bungeecord Side error

This server is different server make this https://github.com/Shevchik/ProtocolSupportBungee/issues/5 issue. that server is fine 

16:37:51 [심각] [swan201] <-> DownstreamBridge <-> [Lobby] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown packet id: 126
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:358)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unknown packet id: 126
	at protocolsupport.protocol.transformer.v_1_5.reader.NonDefinedPacketReader.readPacket(NonDefinedPacketReader.java:87)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.reader.PacketReader.readPacket(PacketReader.java:95)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketDecoder.decode(PacketDecoder.java:35)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
	... 14 more
16:37:51 [정보] [swan201] <-> DownstreamBridge <-> [Lobby] has disconnected
16:37:51 [정보] [swan201] <-> ServerConnector [Wild] has connected
16:37:51 [정보] [swan201] -> UpstreamBridge has disconnected
16:38:21 [정보] [swan201] disconnected with: §f[Proxy] Lost connection to server.
16:38:21 [정보] [swan201] <-> DownstreamBridge <-> [Wild] has disconnected

And Bukkit Side eroor I m open issue

**Comment by JamerBadal** [comment]
I also got that issue @swan201  can you help me?
